<?php
return [
    [
        "route" => "admin/lakecms/index",
        "method" => "GET",
        "type" => 2,
        "is_menu" => 1,
        "title" => "内容管理",
        "icon" => "icon-shiyongwendang",
        "tip" => "",
        "listorder" => 10,
        "child" => [
            [
                "route" => "admin/lakecms/index",
                "method" => "GET",
                "type" => 1,
                "is_menu" => 1,
                "title" => "管理内容",
                "icon" => "icon-neirongguanli",
                "listorder" => 10,
                "child" => [
                    [
                        "route" => "admin/lakecms/panl",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "面板",
                    ],
                    [
                        "route" => "admin/lakecms/cate",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "栏目列表",
                    ],
                    [
                        "route" => "admin/lakecmsContent/add",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "添加",
                        "child" => [
                            [
                                "route" => "admin/lakecmsContent/add",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加",
                            ],
                        ],
                    ],
                    [
                        "route" => "admin/lakecmsContent/edit",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "编辑",
                        "child" => [
                            [
                                "route" => "admin/lakecmsContent/edit",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑",
                            ],
                        ],
                    ],
                    [
                        "route" => "admin/lakecmsContent/delete",
                        "method" => "POST",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "删除",
                    ],
                    [
                        "route" => "admin/lakecmsContent/sort",
                        "method" => "POST",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "排序",
                    ],
                    [
                        "route" => "admin/lakecmsContent/state",
                        "method" => "POST",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "设置状态",
                    ],
                ],
            ],
            
            [
                "route" => "admin/lakecms/index",
                "method" => "GET",
                "type" => 1,
                "is_menu" => 1,
                "title" => "模块设置",
                "icon" => "icon-shiyongwendang",
                "listorder" => 20,
                "child" => [
                    [
                        "route" => "admin/lakecmsNavbar/index",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 1,
                        "title" => "导航设置",
                        "icon" => "icon-liebiaosousuo",
                        "listorder" => 10,
                        "child" => [
                            [
                                "route" => "admin/lakecmsNavbar/index",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "导航设置",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/tree",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "导航结构",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/add",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加导航",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/add",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加导航",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/edit",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑导航",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/edit",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑导航",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/delete",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "删除导航",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/sort",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "导航排序",
                            ],
                            [
                                "route" => "admin/lakecmsNavbar/state",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "状态设置",
                            ],
                        ],
                    ],
                    
                    [
                        "route" => "admin/lakecmsTags/index",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 1,
                        "title" => "标签管理",
                        "icon" => "icon-label",
                        "listorder" => 30,
                        "child" => [
                            [
                                "route" => "admin/lakecmsTags/add",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加标签",
                            ],
                            [
                                "route" => "admin/lakecmsTags/add",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加标签",
                            ],
                            [
                                "route" => "admin/lakecmsTags/edit",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑标签",
                            ],
                            [
                                "route" => "admin/lakecmsTags/edit",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑标签",
                            ],
                            [
                                "route" => "admin/lakecmsTags/delete",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "删除标签",
                            ],
                        ],
                    ],
                    
                    [
                        "route" => "admin/lakecmsCategory/index",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 1,
                        "title" => "栏目管理",
                        "icon" => "icon-other",
                        "listorder" => 50,
                        "child" => [
                            [
                                "route" => "admin/lakecmsCategory/add",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加栏目",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/add",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加栏目",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/edit",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑栏目",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/edit",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "编辑栏目",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/delete",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "删除栏目",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/public_cache",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "更新栏目",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/sort",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "排序",
                            ],
                            [
                                "route" => "admin/lakecmsCategory/state",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "状态设置",
                            ],
                        ],
                    ],
                    
                    [
                        "route" => "admin/lakecmsField/index",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "字段管理",
                        "icon" => "icon-apartment",
                        "listorder" => 60,
                        "child" => [
                            [
                                "route" => "admin/lakecmsField/index",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段管理",
                            ],
                            [
                                "route" => "admin/lakecmsField/add",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段添加",
                            ],
                            [
                                "route" => "admin/lakecmsField/add",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段添加",
                            ],
                            [
                                "route" => "admin/lakecmsField/edit",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段编辑",
                            ],
                            [
                                "route" => "admin/lakecmsField/edit",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段编辑",
                            ],
                            [
                                "route" => "admin/lakecmsField/delete",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段删除",
                            ],
                            [
                                "route" => "admin/lakecmsField/sort",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段排序",
                            ],
                            [
                                "route" => "admin/lakecmsField/state",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段状态",
                            ],
                            [
                                "route" => "admin/lakecmsField/setsearch",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段搜索",
                            ],
                            [
                                "route" => "admin/lakecmsField/setvisible",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段隐藏",
                            ],
                            [
                                "route" => "admin/lakecmsField/setrequire",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "字段必须",
                            ],
                        ],
                    ],
                    
                    [
                        "route" => "admin/lakecmsModel/index",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 1,
                        "title" => "模型管理",
                        "icon" => "icon-apartment",
                        "listorder" => 70,
                        "child" => [
                            [
                                "route" => "admin/lakecmsModel/add",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加模型",
                            ],
                            [
                                "route" => "admin/lakecmsModel/add",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "添加模型",
                            ],
                            [
                                "route" => "admin/lakecmsModel/edit",
                                "method" => "GET",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "修改模型",
                            ],
                            [
                                "route" => "admin/lakecmsModel/edit",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "修改模型",
                            ],
                            [
                                "route" => "admin/lakecmsModel/delete",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "删除模型",
                            ],
                            [
                                "route" => "admin/lakecmsModel/state",
                                "method" => "POST",
                                "type" => 1,
                                "is_menu" => 0,
                                "title" => "设置状态",
                            ],
                        ],
                    ],
                    
                ],
            ],
            
            
            [
                "route" => "admin/lakecmsSetting/index",
                "method" => "GET",
                "type" => 1,
                "is_menu" => 1,
                "title" => "网站设置",
                "icon" => "icon-setup",
                "listorder" => 30,
                "child" => [
                    [
                        "route" => "admin/lakecmsSetting/index",
                        "method" => "GET",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "网站设置",
                    ],
                    [
                        "route" => "admin/lakecmsSetting/index",
                        "method" => "POST",
                        "type" => 1,
                        "is_menu" => 0,
                        "title" => "网站设置",
                    ],
                ],
            ],
            
        ],
    ],
];
